import Image from "./default.png";

const items = [
  {
    image: Image,
    title: "Upsalla",
    description: "Wetin dey sup gan gan",
    cta: "linktofullpreview",
  },
  {
    image: Image,
    title: "Upsalla",
    description: "Wetin dey sup gan gan",
    cta: "linktofullpreview",
  },
  {
    image: Image,
    title: "Upsalla",
    description: "Wetin dey sup gan gan",
    cta: "linktofullpreview",
  },
  {
    image: Image,
    title: "Upsalla",
    description: "Wetin dey sup gan gan",
    cta: "linktofullpreview",
  },
];
